from __future__ import annotations

from app.job_origin import JOB_ORIGIN_AUTOMATIC_TOPIC, JOB_ORIGIN_READY_SCRIPT_BANK

JOB_STATUS_MONETIZATION_REVIEW = "monetization_review"
JOB_STATUS_BLOCKED_FOR_MONETIZATION = "blocked_for_monetization"
JOB_STATUS_READY_FOR_UPLOAD = "ready_for_upload"
JOB_STATUS_APPROVED_FOR_PUBLISH = "approved_for_publish"
JOB_STATUS_UNSCHEDULED_APPROVED = "unscheduled_approved"
JOB_STATUS_SCHEDULED_PUBLICATION = "scheduled_publication"
JOB_STATUS_PUBLISHED = "published"
JOB_STATUS_REJECTED = "rejected"
JOB_STATUS_FAILED = "failed"
JOB_STATUS_QUEUED = "queued"
JOB_STATUS_RUNNING = "running"
JOB_STATUS_SCRIPT_QUALITY_FAILED = "script_quality_failed"
JOB_STATUS_SCENE_PLAN_QUALITY_FAILED = "scene_plan_quality_failed"
JOB_STATUS_SUBTITLE_QUALITY_FAILED = "subtitle_quality_failed"

PUBLISHABLE_JOB_STATUSES = {
    JOB_STATUS_MONETIZATION_REVIEW,
    JOB_STATUS_READY_FOR_UPLOAD,
    JOB_STATUS_APPROVED_FOR_PUBLISH,
}
REPETITION_HISTORY_JOB_STATUSES = {
    JOB_STATUS_READY_FOR_UPLOAD,
    JOB_STATUS_APPROVED_FOR_PUBLISH,
    JOB_STATUS_PUBLISHED,
}
NEEDS_ACTION_JOB_STATUSES = {
    JOB_STATUS_MONETIZATION_REVIEW,
    JOB_STATUS_READY_FOR_UPLOAD,
    JOB_STATUS_BLOCKED_FOR_MONETIZATION,
    JOB_STATUS_REJECTED,
    JOB_STATUS_FAILED,
}

PUBLICATION_STATUS_SCHEDULED = "scheduled"
PUBLICATION_STATUS_PUBLISHING = "publishing"
PUBLICATION_STATUS_PUBLISH_FAILED = "publish_failed"
PUBLICATION_STATUS_PUBLISHED = "published"
PUBLICATION_STATUS_CANCELLED = "cancelled"
PUBLICATION_STATUS_AWAITING_CONFIRMATION = "awaiting_confirmation"

ACTIVE_PUBLICATION_STATUSES = {
    PUBLICATION_STATUS_SCHEDULED,
    PUBLICATION_STATUS_PUBLISHING,
    PUBLICATION_STATUS_PUBLISHED,
}
ACTIVE_SCHEDULE_STATUSES = ACTIVE_PUBLICATION_STATUSES

AUTOMATION_SOURCE_READY_SCRIPT = JOB_ORIGIN_READY_SCRIPT_BANK
AUTOMATION_SOURCE_AUTO_TOPIC = JOB_ORIGIN_AUTOMATIC_TOPIC
AUTOMATION_SOURCE_RESUME = "resume_publish"
AUTOMATION_SOURCE_BACKLOG = "publishable_backlog"

REASON_VISUAL_REVIEW_REQUIRED = "visual_review_required"
REASON_ASSET_VISUAL_REVIEW_REQUIRED = "asset_visual_review_required"
REASON_UNSUPPORTED_CLAIM = "unsupported_claim"
REASON_INVENTED_SOURCE_FACT_IDS = "invented_source_fact_ids"
REASON_OFF_TOPIC = "off_topic"
REASON_WEAK_ENDING = "weak_ending"
REASON_DISALLOWED_SPLIT_OR_COLLAGE_COMPOSITION = "disallowed_split_or_collage_composition"
REASON_P95_TIMING_DRIFT_TOO_HIGH = "p95_timing_drift_too_high"
REASON_MAX_TIMING_DRIFT_TOO_HIGH = "max_timing_drift_too_high"
REASON_SEMANTIC_ORPHAN_START = "semantic_orphan_start"

VISUAL_REVIEW_REQUIREMENTS = {
    REASON_VISUAL_REVIEW_REQUIRED,
    REASON_ASSET_VISUAL_REVIEW_REQUIRED,
}
TEXTUAL_REPAIR_REASONS = {
    REASON_UNSUPPORTED_CLAIM,
    REASON_INVENTED_SOURCE_FACT_IDS,
    REASON_OFF_TOPIC,
    REASON_WEAK_ENDING,
}
SCENE_PLAN_REPAIR_REASONS = {REASON_DISALLOWED_SPLIT_OR_COLLAGE_COMPOSITION}
SUBTITLE_REPAIR_REASONS = {
    REASON_P95_TIMING_DRIFT_TOO_HIGH,
    REASON_MAX_TIMING_DRIFT_TOO_HIGH,
    REASON_SEMANTIC_ORPHAN_START,
}

ARTIFACT_PUBLISH_PACKAGE = "publish_package.json"
ARTIFACT_MONETIZATION_REPORT = "monetization_report.json"
ARTIFACT_AUTOAPPROVAL_SCORE = "autoapproval_score.json"
ARTIFACT_TREND_RESEARCH = "trend_research.json"
